name: Deploy Frontend
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Rename dist to frontend
        run: |
          mv dist frontend

      - name: Remove old frontend directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "rm -rf /home/${{ secrets.USERNAME }}/app/frontend"

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./frontend"
          target: /home/${{ secrets.USERNAME }}/app
          debug: true

      - name: Reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            set -e
            echo "Reloading nginx..."
            cd /home/${{ secrets.USERNAME }}/app
            docker compose exec nginx nginx -s reload
            echo "Deployment completed successfully🚀🚀🚀"
